### ISSUE TITLE
Testing for Unicode Support requires write access to hadoopy install

### ISSUE THREAD

**Issue by amiller** [bwhite/hadoopy#11]
I use sudo python setup.py install, which causes a unicode test to fail.
 IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.6/dist-packages/hadoopy/thirdparty/pyinstaller/support/useUnicode.py'

More context here: https://gist.github.com/800678

**Comment by amiller** [comment]
Full context here: https://gist.github.com/800768

**Comment by bwhite** [comment]
This should fix it https://github.com/bwhite/hadoopy/commit/47e5ecd4ad6201a0d8a0502bd994697c53ac6d56

**Comment by bwhite** [comment]
I believe the above patch fixed this, let me know otherwise
