### ISSUE TITLE
Issue with TypedBytesWritable class of Hadoop

### ISSUE THREAD

**Issue by shreelock** [bwhite/hadoopy#80]
I ran the wrodcount program as given in hadoopy tutorial, the output 'part-00000' was in SequecncefileFormat'. so i tried converting it into textfile by using 

hadoop -text /path/to/part-00000

but instead, I got following error -

text: java.io.IOException: WritableName can't load class: org.apache.hadoop.typedbytes.TypedBytesWritable

How to get rid of this?

**Comment by bwhite** [comment]
You need to be using a version of hadoop that has typed bytes.  CDH
supports it and some versions of apache do too.  What version do you have?
 Also using -text isn't recommended  look into using list(hadoopy.readtb('
/path/to/part-00000'))

**Comment by shreelock** [comment]
I am using hadoop-1.2.1.

Can we include TypedbytesWritable class(as given in apache's website) in a previously installed version?

**Comment by bwhite** [comment]
Not sure, I've only used CDH with this but other have had success with
apache versions.

**Comment by shreelock** [comment]
Can you please explain how to use list(hadoopy.readtb(' /path/to/part-00000')) ? Its giving me syntax error as such.

**Comment by bwhite** [comment]
There is a space in the path so that may be it, if you post the errors I
can help but I don't know what errors you are referring to

**Comment by shreelock** [comment]
I ran this - 
list(hadoopy.readtb('/user/hduser/out3/part-00000'))

Error-
bash: syntax error near unexpected token `hadoopy.readtb'

**Comment by bwhite** [comment]
Sorry you need to run that in python, I recommend reading the docs at
hadoopy.com
